apiVersion: batch/v1
kind: Job
metadata:
  name: k6-job
spec:
  template:
    spec:
      containers:
        - name: k6
          image: loadimpact/k6:latest
          command: ["k6", "run", "--out", "json=/test-results/results.json", "/test-scripts/test.js"]
          volumeMounts:
            - name: test-script
              mountPath: /test-scripts
            - name: results-volume
              mountPath: /test-results
      restartPolicy: OnFailure
      volumes:
        - name: test-script
          hostPath:
            path: /mnt/test-scripts
        - name: results-volume
          persistentVolumeClaim:
            claimName: results-pvc


